services:
  db:
    image: "postgres:15.3"
    volumes:
      - "./misc/sql:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=seccamp
